refactor make, add global git hooks

diff --git a/home/cli/git/hooks/prepare-commit-msg b/home/cli/git/hooks/prepare-commit-msg
--- a/home/cli/git/hooks/prepare-commit-msg
+++ b/home/cli/git/hooks/prepare-commit-msg
@@ -1,16 +1,30 @@
 #!/usr/bin/env bash
 
+hook_name=$(basename $0)
+local=./.git/hooks/$hook_name
+[ -x $local ] && [ -f $local ] && {
+    exec $local
+}
+
 COMMIT_MSG_FILE=$1
 COMMIT_SOURCE=$2
 SHA1=$3
 
-# prefer local hook
-
+# NOTE note that COMMIT_MSG_FILE only has comments when it's invoked interactively
+# meanwhile with `commit -m` it already contains the message
 signature="Co-Authored-By: Claude <noreply@anthropic.com>" 
-commit_msg=$(perl -0777 -pe "s/\n${signature/@/\\@}\n/\n/g" "$COMMIT_MSG_FILE")
-
 if [ -n "$CLAUDE" ]; then
-    if [ -s "$COMMIT_MSG_FILE" ]; then
-	printf '%s\n\n%s' "$commit_msg" "$signature" > "$COMMIT_MSG_FILE"
-    fi
+        if [ "$COMMIT_SOURCE" = "commit" ]; then
+                echo 'permission error: `claude` is not allowed to use `git commit` with flags `-c`, `-C`, or `--amend`'
+                exit 1
+        fi
+        if ! [ -s "$COMMIT_MSG_FILE" ]; then
+                echo 'error: empty commit message'
+                exit 1
+        fi
+        if grep -q "$signature" "$COMMIT_MSG_FILE"; then
+                echo 'assertion error: commit already contains "Co-Authored-By: Claude" trailer'
+                exit 1
+        fi
+	printf '\n%s' "$signature" >> "$COMMIT_MSG_FILE"
 fi
